version: '3.8'

services:
  grpc-mapreduce:
    build:
      context: ..
      dockerfile: docker/Dockerfile.grpc.mapreduce
    container_name: grpc-mapreduce
    environment:
      - MAPREDUCE_PORT=50051
      - MERGESORT_ADDRESS=grpc-mergesort:50053
    ports:
      - "50051:50051"
    networks:
      - grpc-network
    restart: unless-stopped

  grpc-mergesort:
    build:
      context: ..
      dockerfile: docker/Dockerfile.grpc.mergesort
    container_name: grpc-mergesort
    environment:
      - MERGESORT_PORT=50053
      - STATISTICS_ADDRESS=grpc-statistics:50055
    ports:
      - "50053:50053"
    networks:
      - grpc-network
    restart: unless-stopped
    depends_on:
      - grpc-mapreduce

  grpc-statistics:
    build:
      context: ..
      dockerfile: docker/Dockerfile.grpc.statistics
    container_name: grpc-statistics
    environment:
      - STATISTICS_PORT=50055
    ports:
      - "50055:50055"
    networks:
      - grpc-network
    restart: unless-stopped
    depends_on:
      - grpc-mergesort

  grpc-client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.grpc.client
    container_name: grpc-client
    environment:
      - MAPREDUCE_ADDRESS=grpc-mapreduce:50051
      - OUTPUT_FILE=/app/results/grpc_docker_performance_metrics.json
    volumes:
      - ../results:/app/results
    networks:
      - grpc-network
    depends_on:
      - grpc-mapreduce
      - grpc-mergesort
      - grpc-statistics

networks:
  grpc-network:
    driver: bridge

