version: '3.8'

services:
  xmlrpc-server:
    image: xmlrpc-server:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.xmlrpc.server
    ports:
      - "8000:8000"
    networks:
      - student-network
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import xmlrpc.client; xmlrpc.client.ServerProxy(\"http://localhost:8000\").system.listMethods()' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  xmlrpc-client:
    image: xmlrpc-client:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.xmlrpc.client
    depends_on:
      - xmlrpc-server
    networks:
      - student-network
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_ADDRESS=http://xmlrpc-server:8000
      - OUTPUT_FILE=/app/results/xmlrpc_swarm_performance_metrics.json
      - WAIT_TIME=15
    volumes:
      - type: bind
        source: ../results
        target: /app/results
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == manager
    command: sh -c "sleep 15 && python client.py"

networks:
  student-network:
    driver: overlay
    attachable: true
