version: '3.8'

services:
  server:
    image: student-analysis-server:latest
    ports:
      - "50051:50051"
    networks:
      - student-network
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  client:
    image: student-analysis-client:latest
    networks:
      - student-network
    volumes:
      - type: bind
        source: ../results
        target: /app/results
    environment:
      - SERVER_ADDRESS=server:50051
      - OUTPUT_FILE=grpc_swarm_performance_metrics.json
      - PYTHONUNBUFFERED=1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
      placement:
        constraints:
          - node.role == manager

networks:
  student-network:
    driver: overlay
    attachable: true
