version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    container_name: student-analysis-server
    ports:
      - "50051:50051"
    networks:
      - student-network
    environment:
      - PYTHONUNBUFFERED=1

  client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.client
    container_name: student-analysis-client
    depends_on:
      - server
    networks:
      - student-network
    environment:
      - SERVER_ADDRESS=server:50051
      - PYTHONUNBUFFERED=1
    volumes:
      - ../results:/app/results

networks:
  student-network:
    driver: bridge
